### PR TITLE
Nico

### PR DESCRIPTION
**Pull request by blacksph3re**
Here ist what I did to the slides for my java-course, you can have a look at it if you want.
I did not clean up the res folder. And as I started with the old slides, the old slides are still in the branch. If you really want i can do a cleanup, but I'd prefer not to ^^

### CODE REVIEW

**Comment by JustusAdam** [comment]
It seems you're addressing a specific person, why not 'mention' them using '@username' so that they'll get a notification.

**Comment by blacksph3re** [comment]
Jeah, should be Manuel, but I could not find his username.

**Comment by JustusAdam** [comment]
@manuelthieme

**Comment by blacksph3re** [comment]
thx

**Pull request merged**
